repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-added-large-files
        args: ["--maxkb=100"]
    -   id: trailing-whitespace

-   repo: https://github.com/asottile/pyupgrade
    rev: v2.29.0
    hooks:
    -   id: pyupgrade
        args: ["--py38-plus"]

-   repo: https://github.com/psf/black
    rev: 21.10b0
    hooks:
    -   id: black-jupyter

-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-bugbear, flake8-import-order, flake8-print]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910-1
    hooks:
    -   id: mypy
        files: src/simplify
