coverage:
  status:
    project:
      default:
        threshold: 1.0%
    patch:
      default:
        enabled: no
  ignore:
    - "src/simplify/_version.py"
    - "src/simplify/__init__.py"
    - "src/simplify/benchmark.py"
    - "src/simplify/exceptions.py"
    - "src/simplify/cli/__init__.py"
